services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Novactive\EzMenuManager\Form\Type\FieldType\MenuItemFieldType: ~
    Novactive\EzMenuManager\Form\Type\FieldType\FieldValueTransformer: ~

    Novactive\EzMenuManager\Persistence\Legacy\Content\FieldValue\Converter\MenuItemConverter:
        tags:
            - {name: ezpublish.storageEngine.legacy.converter, alias: menuitem}
