services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Novactive\EzMenuManager\FieldType\MenuItem\SearchField:
        tags:
            - {name: ezpublish.fieldType.indexable, alias: menuitem}
