services:
    ezmenumanager.ezadminui.component.stylesheets:
         parent: EzSystems\EzPlatformAdminUi\Component\TwigComponent
         arguments:
            $template: '@@EzMenuManager/themes/standard/ezadminui/stylesheets.html.twig'
         tags:
             - { name: ezplatform.admin_ui.component, group: 'stylesheet-head' }
